Minimal petsc4py code for ksp
pmgbergen/DarSIA pull request #370
Opened 2024-08-22 17:25 UTC by enricofacca

Minimal code using petsc4py and ksp solver for linear systems.

Test add to test_wasserstein

2024-08-26 21:47 UTC, jwboth requested changes
Thanks a lot, Enrico! This looks really good. Most comments are curiosity questions, me wanting to better understand what is going on. 

Most critical is the failing installation of DarSIA including petsc4py. The style (black etc.) will sort out. I can take care of that once the installation is fixed.

2024-08-26 21:47 UTC, jwboth commented on src/darsia/utils/linalg.py
> +        self.A_petsc += zero_diagonal
Less prioritized for now.

2024-08-26 21:47 UTC, jwboth commented on src/darsia/utils/linalg.py
> +        self.prefix = "petsc_solver_"
Does this has implications for how to define the options of the solver from the outside?

2024-08-26 21:47 UTC, jwboth commented on requirements.txt
> +petsc4py
Based on the github actions, github does not manage to install DarSIA including petsc4py. Can you have a look at the installation report? Anything needed in addition?

2024-08-27 08:35 UTC, enricofacca commented on tests/unit/test_wasserstein.py
> +        "approach": "krylov",
Yes

2024-08-27 08:36 UTC, enricofacca commented on src/darsia/measure/wasserstein.py
> +                    self.setup_ksp_solver(self.fully_reduced_matrix)
Yes. Need to be fixed.

2024-08-28 14:55 UTC, enricofacca commented
Some comments on why we are not able to install petsc4py.
Reading [this ](https://pypi.org/project/petsc4py/) we first need to install numpy (than has recently being updated to version 2.0) and mpi4py. 
Than we should install petsc and petsc4py via pip.
I was able to make it work but mumps and hypre are missing. 
It should be possible to include this component using environment variable (as described [here](https://gitlab.com/petsc/petsc/-/blob/main/setup.py?ref_type=heads)) but it does not work.

I was able to make everything work using conda + create env + installing petsc with conda install (pip install inside the env does not work). Hypre and mumps are, by default, included in the conda installation of petsc.

2024-08-28 15:07 UTC, enricofacca commented
It seems that the issue with the inclusion of petsc4py is not so easy to solve.
Following the instruction [here](https://pypi.org/project/petsc4py/) I was was to include petsc4py.
However hypre and mumps are missing. [Here](https://gitlab.com/petsc/petsc/-/blob/main/setup.py?ref_type=heads) it says that it possible to include them using environment variables, but I was able to.

Nevertheless using conda + create env + installing via conda (and not via pip within the env) I was able to install petsc, hypre and mumps , since they are included by default.

2024-08-28 19:38 UTC, jwboth commented
I removed petsc4py and cython from the requirements. Instead, now petsc4py (at least on github actions) is build in the build workflow, see #374 . The installation for Windows will not fully work from command line I fear, and not just using pip. I am trying therefore instead to set up a separate routine for that. Can you check, whether you can run the installation of petsc incl. hypre and mumps as done in the ci script?

2024-08-29 10:54 UTC, enricofacca reviewed
I answered your points. But I just wanted to test the CI. I am not sure I did the review as it supposed to be.

2024-08-29 14:19 UTC, enricofacca commented
Testing works but it took **"30 minutes"** to complete with the inclusion of hypre and mumps. 
This may be a problem if there are limitations on free testing time on Github.

We can just use native petsc solvers (replacing "hypre" with "icc" and mumps with the standard LU factorization), include petsc.  So that the building test is passed and it takes way less time.

However, the installation of mpi4py requires MPI being installed. This may cause problems to some users..

2024-08-29 22:44 UTC, jwboth approved these changes
Looks good for now! Thanks a lot!

2024-08-29 22:45 UTC, merged